### ISSUE TITLE
Some of the music doesn't fully loop and stops abruptly 

### ISSUE THREAD

**Issue by DankMickey** [Toontown-Rewritten-Private/TTR-Private#9]
Some of the sound effects are louder than they should be too, maybe an audio manager issue?

**Comment by DankMickey** [comment]
self.__enterFunc(*argList)
  File "C:\Users\USER\Documents\GitHub\TTR-Private\toontown\distributed\ToontownClientRepository.py", line 223, in enterChooseAvatar
    self.music.setLoopStart(2.9)
AttributeError: 'panda3d.core.AudioSound' object has no attribute 'setLoopStart'
Press any key to continue . . .

The code above might be why the music doesn't loop

**Comment by RegDogg** [comment]
Fixed in https://github.com/Toontown-Rewritten-Private/panda3d/commit/f74c1c1e9ac0cc2114b64be05fcc127cd58e1eb0
